config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "static_pages#home"

  # Chapter/3-4-5
  get "static_pages/home"
  get "static_pages/help"
  get "switch_language/:locale", to: "application#switch_language", as: "switch_language"
  get "up" => "rails/health#show", as: :rails_health_check

  # Chapter/6
  resources :users

  # Chapter/7
  get "sign_up", to: "users#new", as: "sign_up"

  # Chapter/8 + Chapter 9
  get "sessions/new"
  post "sessions/create"
  delete "sessions/destroy", as: "log_out"

  # Chapter/11
  get "activate/:activation_digest", to: "account_activations#edit", as: "activate_user", constraints: { activation_digest: /.*/ }

  # Chapter/12
  resources :password_resets, except: %i(index show), constraints: { id: /.*/ }

  # Chapter/13
  resources :microposts, only: %i(new create destroy)

  # Chapter/14
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: %i(create destroy)
end

app/models/micropost.rb
# frozen_string_literal: true

class Micropost < ApplicationRecord
  belongs_to :user
  has_one_attached :image

  validates :content, presence: true, length: { maximum: Settings["DIGIT_140"] }
  validates :image, content_type: { in: %w[image/jpeg image/gif image/png], message: I18n.t("image.valid_message") }
  scope :recent_posts, -> { order created_at: :desc }
  scope :relate_post, ->(user_ids) { where(user_id: user_ids) }
end

app/controllers/microposts_controller.rb
# frozen_string_literal: true

class MicropostsController < ApplicationController
  before_action :logged_in_user, only: %i(create destroy new)
  before_action :correct_user, only: :destroy

  def new
    @micropost = Micropost.new
  end

  def create
    @micropost = @current_user.microposts.build micropost_params
    @micropost.image.attach params.dig(:micropost, :image)
    if @micropost.save
      flash[:success] = t "create.microposts.success_message"
      redirect_to root_url
    else
      @pagy, @feed_items = pagy current_user.feed, items: Settings["PERPAGE_5"]
      render :new, status: :unprocessable_entity
    end
  end

  def destroy
    if @micropost.destroy
      flash[:success] = t "delete.micropost.success_message"
      redirect_to root_path
    else
      flash[:danger] = t "delete.micropost.fail_message"
      redirect_to request.referer || root_url
    end
  end

  private

  def micropost_params
    params.permit :content, :image
  end

  def correct_user
    @micropost = @current_user.microposts.find_by id: params[:id]
    return if @micropost

    flash[:danger] = t "invalid_message"
    redirect_to request.referrer || root_url
  end
end

app/helpers/microposts_helper.rb
# frozen_string_literal: true

module MicropostsHelper
end

app/views/microposts/_form.html.erb
<%= form_for @micropost do |form| %>
  <%= render partial: "shared/errors_valid", locals: { object: @micropost } %>
  <div class="form-group">
    <label for="name"><%= form.label t(".content") %></label>
    <textarea name="content" id="name" class="form-control" placeholder="<%= t("form.placeholder.content") %>"></textarea>
    <span class="image"><%= form.file_field :image, accept: "image/jpeg,image/gif,image/png", class: "mt-3" %></span>
  </div>
  <button type="submit" class="btn btn-primary mt-3 float-end">
    <%= t "button.create", name: t("button.label_create_micropost") %></button>
<% end %>

app/views/microposts/_micropost.html.erb
<li class="mb-5 d-flex m-auto" id="micropost-<%= micropost.id %>">
  <div class=""><%= link_to gravatar_for(micropost.user, size: Settings["DIGIT_140"]), micropost.user %></div>
  <div class="ms-5">
    <p class="user"><%= link_to micropost.user.name, micropost.user %></p>
    <p class="content"><%= micropost.content %></p>
    <%= image_tag micropost.image if micropost.image.attached? %>
    <p class="timestamp"><%= t "content.posted_time" %> <%= time_ago_in_words micropost.created_at %>
      ago.</p>
  </div>
  <%= button_to t("button.delete"), micropost_path(micropost), method: :delete, class: "btn btn-danger ms-3" %>
</li>

app/views/microposts/new.html.erb
<div class="row">
  <section class="user_info col-4">
    <%= render "shared/profile" %>
  </section>
  <section class="micropost_form col-8">
    <%= render "form" %>
  </section>
</div>