config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root "static_pages#home"

  # Chapter/3-4-5
  get "static_pages/home"
  get "static_pages/help"
  get "switch_language/:locale", to: "application#switch_language", as: "switch_language"
  get "up" => "rails/health#show", as: :rails_health_check

  # Chapter/6
  resources :users

  # Chapter/7
  get "sign_up", to: "users#new", as: "sign_up"

  # Chapter/8 + Chapter 9
  get "sessions/new"
  post "sessions/create"
  delete "sessions/destroy", as: "log_out"

  # Chapter/11
  get "activate/:activation_digest", to: "account_activations#edit", as: "activate_user", constraints: { activation_digest: /.*/ }

  # Chapter/12
  resources :password_resets, except: %i(index show), constraints: { id: /.*/ }

  # Chapter/13
  resources :microposts, only: %i(new create destroy)

  # Chapter/14
  resources :users do
    member do
      get :following, :followers
    end
  end

  resources :relationships, only: %i(create destroy)
end

app/views/layouts/_footer.html.erb
<h1><%= t("footer.footer_name") %></h1>

app/views/layouts/_header.html.erb
<nav class="navbar navbar-expand-lg navbar-light bg-light p-0 m-0 mb-5 ">
  <div class="container-fluid">
    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
            aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
    <div class="collapse navbar-collapse" id="navbarSupportedContent">
      <ul class="navbar-nav me-auto mb-2 mb-lg-0">
        <li class="nav-item">
          <a class="nav-link active" aria-current="page" href="#">
            <%= t("header.home_name") %>
          </a>
        </li>
      </ul>
      <div class="dropdown">
        <button class="btn btn-success dropdown-toggle" type="button" id="dropdownMenuButton1" data-bs-toggle="dropdown" aria-expanded="false">
          <%= t "button.setting" %>
        </button>
        <ul class="dropdown-menu" aria-labelledby="dropdownMenuButton1">
          <% if logged_in? %>
            <li><%= link_to t("user.title_all_user"), users_path, class: "dropdown-item" %></li>
            <li><%= link_to t("user.title_show_information"), @current_user, class: "dropdown-item" %></li>
            <li><%= link_to t("user.title_update_information"), edit_user_path(@current_user), class: "dropdown-item" %></li>
            <li><%= button_to t("button.logout"), log_out_path, method: :delete, class: "dropdown-item" %></li>
          <% else %>
            <li><%= link_to t("button.login"), sessions_new_path, class: "dropdown-item" %></li>
          <% end %>
        </ul>
      </div>
    </div>
  </div>
</nav>

app/views/layouts/_language.html.erb
<ul>
  <li>
    <%= link_to t("application.language.en") , switch_language_path(:en) %>
  </li>
  <li>
    <%= link_to t("application.language.vi") , switch_language_path(:vi) %>
  </li>
</ul>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>
    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>
  <body>
    <div class="container">
      <div>
        <%= render "layouts/header" %>
        <%= render "layouts/language" %>
      </div>
      <div>
        <div class="col-3 m-auto"><%= render partial: "shared/flash_messages" %></div>
        <%= yield %>
      </div>
      <div>
        <%= render "layouts/footer" %>
      </div>
    </div>
  </body>
</html>